INSERT INTO atlassian.issues_info
SELECT issue_id,
       issue_key,
       project_key,
       issuetype_name,
       priority_name,
       status_name,
       resolution_name,
       JSONExtract(components_json, 'Array(String)')   components,
       is_lts,
       JSONExtract(versions_json, 'Array(String)')     versions,
       JSONExtract(fix_versions_json, 'Array(String)') fix_versions,
       assignee_name,
       assignee_key,
       reporter_name,
       reporter_key,
       creator_name,
       creator_key,
       votes,
       created,
       updated,
       resolutiondate,
       days_to_close,
       created_year,
       created_month,
       created_week,
       created_day,
       resolved_year,
       resolved_month,
       resolved_week,
       resolved_day,
       etl_time
FROM atlassian.issues_info_temp
