#Airflow variables


# ATLASSIAN variables
ATLASSIAN_AUTH_TOKEN_VAR_NAME = 'ATLASSIAN_AUTH_TOKEN'
ATLASSIAN_JIRA_URL = "https://jira.atlassian.com"
API_SEARCH_METHOD_PATH = "rest/api/2/search`"
CLOUD_PROJECT_KEY = "JRACLOUD"
SRV_PROJECT_KEY = "JRASERVER"
PLAIN_JQL = f"project in ({SRV_PROJECT_KEY},{CLOUD_PROJECT_KEY}) ORDER BY updated ASC"

# PG variables
DWH_CONNECTION_NAME = "atlas_stg_db"

